export const RULE = 'evidence-v1';
export const MODES = ['demo', 'imported', 'live'];
export const PAPER_DISABLED = '云端版本未启用模拟撮合、分批止盈或移动止盈。Python v2 已实现相关测试，但未迁移至云端账本。这里不会生成模拟订单或成交。';
const STAGES = ['unknown','application','pilot','order','revenue','other'];
const EXPECTATIONS = ['unknown','above','in_line','below','priced_in'];
const REACTIONS = ['unknown','up','flat','down'];
const DISCLAIMER = '事实阶段、相对预期与价格反应独立记录，互不证明；系统不独立核验原文，不生成买卖指令。';
export function initialState() { return { mode:'imported', watchlist:[], snapshots:[], news:[], portfolio:[], alerts:[], runs:[], audit:[], sequence:0 }; }
function assert(ok, text) { if(!ok) throw new Error(text); }
export function finite(v, name, min=-Infinity) { assert(typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=1e15&&v>=min, `${name} 必须是有效有限数值`); return v; }
export function timestamp(v) { assert(typeof v==='string'&&/(Z|[+-]\d\d:\d\d)$/.test(v)&&Number.isFinite(Date.parse(v)), '时间必须是带时区的 ISO 8601 字符串'); return new Date(v).toISOString(); }
function text(v, limit=3000) { assert(typeof v==='string'&&v.length<=limit, `文本长度须在 ${limit} 字符内`); return v.trim(); }
function symbol(v, demo=false) { assert(typeof v==='string'&&(/^[0-9]{6}$/.test(v)||(demo&&/^DEMO0[1-4]$/.test(v))), '证券代码须为六位数字'); return v; }
function url(v, optional=false) { if(!v&&optional)return ''; let u; try {u=new URL(v)}catch{} assert(u&&u.protocol==='https:'&&!u.username&&!u.password&&String(v).length<=1500, '来源必须是无凭据的 HTTPS 链接');return String(v); }
function shanghaiDay(v){return new Date(Date.parse(v)+8*3600000).toISOString().slice(0,10)}
function audit(s, action, target, detail, now){s.audit.unshift({id:++s.sequence,at:now,action,target,detail:JSON.stringify(detail)});}
export function freshness(s, now) {const age=(Date.parse(now)-Date.parse(s.observed_at))/60000;return {state:age<0?'invalid':s.mode==='demo'?'demo':age<=20?'fresh':'stale',age_minutes:Math.max(0,Math.round(age*10)/10),label:age<0?'未来时间 · 禁止触发':s.mode==='demo'?'虚构样本 · 非实时行情':age<=20?'时间窗内':'数据已过期 · 禁止触发'};}
export function validateSnapshot(d, mode, now){
 assert(d&&typeof d==='object'&&!Array.isArray(d),'行情必须是对象');
 const s={symbol:symbol(d.symbol,mode==='demo'),mode,observed_at:timestamp(d.observed_at),source:text(d.source,150),source_url:url(d.source_url,mode==='demo'),fetched_at:now};
 assert(s.source,'每条行情须注明来源');assert(Date.parse(s.observed_at)<=Date.parse(now),'不接受未来行情');
 for(const k of ['price','turnover','volume']) s[k]=finite(d[k],k,0);
 s.change_pct=finite(d.change_pct,'change_pct');s.large_order_net=d.large_order_net==null?null:finite(d.large_order_net,'large_order_net');
 s.flow_definition=text(d.flow_definition||'',500);if(s.large_order_net!=null){assert(s.flow_definition,'资金流须提供供应商统计口径');assert(Math.abs(s.large_order_net)<=s.turnover,'大单净额不可超过成交额');}
 assert(Array.isArray(d.baseline||[])&&(d.baseline||[]).length<=120,'baseline 最多 120 项');s.baseline=(d.baseline||[]).map(v=>finite(v,'baseline',0));s.baseline_basis=text(d.baseline_basis||'',500);assert(!s.baseline.length||s.baseline_basis,'基线须说明同窗单位和统计口径');
 assert(Array.isArray(d.series||[])&&(d.series||[]).length<=60,'series 最多 60 项');s.series=(d.series||[]).map(v=>finite(v,'series',0));return s;
}
export function anomaly(s, now){
 if(!['fresh','demo'].includes(freshness(s,now).state)||s.baseline.length<20||s.turnover<=0)return null;
 const mean=s.baseline.reduce((a,b)=>a+b,0)/s.baseline.length,std=Math.sqrt(s.baseline.reduce((a,b)=>a+(b-mean)**2,0)/s.baseline.length);if(mean<=0||std<=0)return null;
 const ratio=s.turnover/mean,z=(s.turnover-mean)/std,flow=s.large_order_net==null?null:s.large_order_net/s.turnover;let score=0;const evidence=[];
 if(ratio>=1.8&&z>=2.5){score+=40;evidence.push(`同窗成交额为 ${s.baseline.length} 项基线均值的 ${ratio.toFixed(2)} 倍；Z=${z.toFixed(2)}`)}
 if(flow!=null&&Math.abs(flow)>=.08){score+=30;evidence.push(`供应商大单净额/成交额 ${(flow*100).toFixed(1)}%（${s.flow_definition}）`)}
 if(flow!=null&&((flow>0&&s.change_pct<0)||(flow<0&&s.change_pct>0))){score+=15;evidence.push('价格与供应商大单统计方向相反')}
 if(score<55)return null;
 return {score,title:`量能放大与大单${flow>0?'流入':'流出'}同时出现`,evidence,volume_ratio:Math.round(ratio*100)/100,z_score:Math.round(z*100)/100,flow_ratio:flow,snapshot_at:s.observed_at,source:s.source,source_url:s.source_url,rule_version:RULE,hypothesis:'交易活跃度与大单统计异常，不足以识别机构身份、吸筹或洗盘。',counter_evidence:['板块或指数整体波动可能造成共同异动','调仓、集中成交或分类口径差异可产生相似信号'],invalidation:['后续成交额比值低于 1.2','大单方向反转或统计修订','数据超过 20 分钟、基线不可比或来源不可用'],question:'是否加入人工复核清单，核对证据与自身风险约束？',disclaimer:'规则关注分，不是上涨概率、收益预测或买卖指令'};
}
function saveAlert(s,code,mode,kind,payload,key,now){const fingerprint=JSON.stringify([mode,code,kind,key,RULE]);let old=s.alerts.find(a=>a.fingerprint===fingerprint);if(old){Object.assign(old,{payload,title:payload.title,score:payload.score,updated_at:now});return 0;}s.alerts.push({id:++s.sequence,fingerprint,symbol:code,mode,kind,title:payload.title,score:payload.score,status:'new',created_at:now,updated_at:now,payload});audit(s,'alert_created',code,{mode,kind,event:key},now);return 1;}
export function assessment(n){const missing=[];if(['unknown','other'].includes(n.stage)||!n.evidence_excerpt)missing.push('factual_stage_evidence');if(n.verification!=='reviewed'||!n.reviewed_by)missing.push('human_source_review');if(n.expectation_status==='unknown'||!n.expectation_evidence)missing.push('expectation_evidence');if(n.price_reaction==='unknown'||!n.price_reaction_evidence)missing.push('price_reaction_evidence');return {action:'HOLD',status:missing.length?'insufficient_evidence':'manual_review_only',missing_fields:missing,reason:missing.length?'证据或分类未知，保持 HOLD，等待人工研究。':'人工证据已记录，仍保持 HOLD；不自动推导买卖或收益优势。',disclaimer:DISCLAIMER};}
export function validateNews(d,now){
 const n={symbol:symbol(d.symbol),title:text(d.title,200),mode:'imported',source_url:url(d.source_url),source:text(d.source||'手工录入',150),published_at:timestamp(d.published_at||now),stage:d.stage||'unknown',verification:d.verification||'unverified',reviewed_by:text(d.reviewed_by||'',60),evidence_excerpt:text(d.evidence_excerpt||''),note:text(d.note||'',1000),amount:text(d.amount||'',80),expectation_status:d.expectation_status||'unknown',expectation_evidence:text(d.expectation_evidence||''),price_reaction:d.price_reaction||'unknown',price_reaction_evidence:text(d.price_reaction_evidence||''),analysis_schema_version:2};
 assert(n.title,'标题不能为空');assert(Date.parse(n.published_at)<=Date.parse(now),'不接受未来新闻');assert(STAGES.includes(n.stage),'无效事实阶段');assert(['unverified','linked','reviewed'].includes(n.verification),'无效核验状态');assert(EXPECTATIONS.includes(n.expectation_status)&&REACTIONS.includes(n.price_reaction),'无效预期或价格分类');
 assert(['unknown','other'].includes(n.stage)||n.evidence_excerpt,'事实阶段须有原文依据，不能以价格代替');assert(n.verification!=='reviewed'||(n.reviewed_by&&n.evidence_excerpt),'人工核验须填写核验人和原文');assert(n.expectation_status==='unknown'||n.expectation_evidence,'预期分类须填写事前比较基准、时间与证据');assert(n.price_reaction==='unknown'||n.price_reaction_evidence,'价格反应须有观察窗口、来源与证据');n.research_assessment=assessment(n);return n;
}
export function parsePortfolio(csv, now){
 assert(typeof csv==='string'&&csv.length<=500000,'CSV 超过大小限制');const rows=[];let row=[],cell='',quoted=false;csv=csv.replace(/^\uFEFF/,'');
 for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){cell+='"';i++}else{assert(quoted||!cell,'无效 CSV 引号');quoted=!quoted}}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&csv[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x))rows.push(row);row=[];cell=''}else cell+=c;}
 assert(!quoted,'CSV 引号未闭合');if(cell||row.length){row.push(cell);rows.push(row)}
 const header=rows.shift();assert(header?.join(',')==='symbol,name,shares,cost','表头必须恰好为 symbol,name,shares,cost；不要上传账户或身份信息');assert(rows.length>=1&&rows.length<=200,'CSV 必须有 1–200 行');const seen=new Set();return rows.map(r=>{assert(r.length===4,'CSV 必须恰好四列');const code=symbol(r[0].trim());assert(!seen.has(code),'证券代码不可重复');seen.add(code);assert(r[2].trim()&&r[3].trim(),'股数与成本不能为空');return {symbol:code,name:text(r[1],50),shares:finite(Number(r[2]),'shares',0),cost:finite(Number(r[3]),'cost',0),imported_at:now};});
}
function demoSnapshots(now){return ['DEMO01','DEMO02','DEMO03','DEMO04'].map((code,i)=>validateSnapshot({symbol:code,observed_at:now,source:'当次生成的虚构样本',price:[38.62,21.35,15.08,46.7][i],volume:1e7,turnover:[2.43e8,2.05e8,1.16e8,.94e8][i],change_pct:[-1.32,2.14,.46,-.73][i],large_order_net:[3.41e7,-2.25e7,4e6,-3e6][i],flow_definition:'虚构的成交金额分类，并非机构资金',baseline:Array.from({length:20},(_,j)=>(1+(j%7-3)*.047)*1e8),baseline_basis:'虚构历史同时间窗，人民币元',series:Array.from({length:24},(_,j)=>100+Math.sin(j*.7+i)*.45+j*.02)},'demo',now));}
function latest(s,mode){const items={};for(const x of [...s.snapshots].sort((a,b)=>b.observed_at.localeCompare(a.observed_at)))if(x.mode===mode&&!items[x.symbol])items[x.symbol]=x;return items;}
function storeSnapshot(s,item){const index=s.snapshots.findIndex(x=>x.symbol===item.symbol&&x.mode===item.mode&&x.observed_at===item.observed_at&&x.source===item.source);if(index<0)s.snapshots.push(item);else s.snapshots[index]=item;}
export function mutate(s,path,d,now){
 assert(d&&typeof d==='object'&&!Array.isArray(d),'请求必须是对象');let result={saved:true};
 if(path.startsWith('/api/paper/'))throw new Error(PAPER_DISABLED);
 if(path==='/api/mode'){assert(MODES.includes(d.mode),'未知模式');s.mode=d.mode;audit(s,'mode_changed',d.mode,{},now);result={mode:d.mode};}
 else if(path==='/api/watchlist'){const code=symbol(d.symbol?.trim(),true),name=text(d.name,50);assert(name,'名称不能为空');const old=s.watchlist.find(w=>w.symbol===code),w={symbol:code,name,enabled:d.enabled===false?0:1,added_at:old?.added_at||now};if(old)Object.assign(old,w);else {assert(s.watchlist.length<200,'自选最多 200 项');s.watchlist.push(w)}audit(s,'watchlist_saved',code,{name},now);}
 else if(path==='/api/watchlist/remove'){const code=symbol(d.symbol,true);s.watchlist=s.watchlist.filter(w=>w.symbol!==code);audit(s,'watchlist_removed',code,{},now);result={removed:true};}
 else if(path==='/api/import/market'){assert(Array.isArray(d.snapshots)&&d.snapshots.length>0&&d.snapshots.length<=100,'行情须为 1–100 项数组');const items=d.snapshots.map(x=>validateSnapshot(x,'imported',now));items.forEach(x=>storeSnapshot(s,x));audit(s,'market_import',String(items.length),{count:items.length},now);result={count:items.length};}
 else if(path==='/api/import/portfolio'){const rows=parsePortfolio(d.csv,now);s.portfolio=rows;audit(s,'portfolio_import','private_csv',{count:rows.length},now);result={count:rows.length};}
 else if(path==='/api/news'){const n=validateNews(d,now),old=s.news.find(x=>x.symbol===n.symbol&&x.source_url===n.source_url&&x.title===n.title);n.id=old?.id||`news-${++s.sequence}`;if(old)Object.assign(old,n);else s.news.push(n);const age=(Date.parse(now)-Date.parse(n.published_at))/3600000;let count=0;if(n.verification==='reviewed'&&['order','revenue'].includes(n.stage)&&age>=0&&age<=72){count=saveAlert(s,n.symbol,'imported','news',{title:n.title,score:n.stage==='order'?70:85,evidence:[`用户人工核验：${n.reviewed_by}`,n.evidence_excerpt,`事实阶段：${n.stage}`],source:n.source,source_url:n.source_url,snapshot_at:n.published_at,rule_version:RULE,hypothesis:'由人工记录触发，系统未独立验证原文或预测利润影响。',counter_evidence:['订单不等于收入，收入不等于利润或回款','检查条件、取消风险、关联交易及相对体量','事实阶段不代表超预期、尚未计价或未来上涨'],invalidation:['公告更正、合同取消或履约条件不满足','原文不支持所标事实阶段'],question:'是否人工复核该事件对现有研究逻辑的影响？',disclaimer:'事件关注分，不是收益概率或交易指令',research_assessment:n.research_assessment},n.id,now)}if(!(n.verification==='reviewed'&&['order','revenue'].includes(n.stage)&&age>=0&&age<=72)){const previous=s.alerts.find(a=>a.kind==='news'&&a.fingerprint===JSON.stringify(['imported',n.symbol,'news',n.id,RULE]));if(previous){previous.score=0;previous.updated_at=now;previous.payload={...previous.payload,score:0,research_assessment:n.research_assessment,evidence:['此前提醒依据已改变；当前记录不再满足事件提醒条件',n.evidence_excerpt||'原文依据已撤回'],hypothesis:'已撤销当前事件提醒资格，保持 HOLD，等待重新人工核验。',snapshot_at:n.published_at};}}audit(s,'news_saved',n.id,{stage:n.stage,expectation_status:n.expectation_status,price_reaction:n.price_reaction,research_action:'HOLD',new_alert:count},now);result={news:n};}
 else if(path==='/api/alerts/status'){assert(['new','reviewed','dismissed'].includes(d.status),'无效提醒状态');const a=s.alerts.find(x=>x.id===d.id);assert(a,'提醒不存在');a.status=d.status;a.updated_at=now;audit(s,'alert_status',String(d.id),{status:d.status,note:text(d.note||'',500)},now);}
 else if(path==='/api/run'){
 const mode=d.mode||s.mode;assert(MODES.includes(mode),'未知模式');s.mode=mode;let scanned=0,stale=0,incomplete=0,count=0,status='ok',detail='';
 if(mode==='live'){status='failed';detail='实时行情适配器未接入；没有回退到演示数据';}
 else {if(mode==='demo'){const names=['示例芯片','示例电网','示例制造','示例消费'];demoSnapshots(now).forEach((x,i)=>{storeSnapshot(s,x);if(!s.watchlist.some(w=>w.symbol===x.symbol))s.watchlist.push({symbol:x.symbol,name:names[i],enabled:1,added_at:now})});}
 const enabled=new Set(s.watchlist.filter(w=>w.enabled).map(w=>w.symbol));for(const x of Object.values(latest(s,mode))){if(!enabled.has(x.symbol))continue;scanned++;if(['stale','invalid'].includes(freshness(x,now).state)){stale++;continue}const p=anomaly(x,now);if(p)count+=saveAlert(s,x.symbol,mode,'flow',p,shanghaiDay(x.observed_at),now);else if(x.baseline.length<20)incomplete++;}status=stale||incomplete||!scanned?'degraded':'ok';detail=`检查 ${scanned} 个标的；新增 ${count} 条异常；${stale} 条过期；${incomplete} 条基线不足${!scanned?'；无可分析数据':''}`;}
 const run={id:++s.sequence,mode,started_at:now,finished_at:now,status,detail};s.runs.unshift(run);audit(s,status==='failed'?'monitor_failed':'monitor_run',String(run.id),{mode,status,new_alerts:count},now);result={status,detail,new_alerts:count,run_id:run.id};}
 else throw new Error('接口不存在；没有实盘交易接口');
 assert(s.snapshots.length<=5000&&s.news.length<=2000&&s.alerts.length<=5000&&s.audit.length<=10000&&s.runs.length<=5000,'工作区已达容量上限，请导出记录后联系维护；本次操作未保存');return result;
}
export function digest(s,now){const today=shanghaiDay(now),alerts=s.alerts.filter(x=>x.mode===s.mode&&shanghaiDay(x.updated_at)===today),run=s.runs.find(x=>x.mode===s.mode);return [`星策 · ${today} 日报`,`模式：${s.mode}（demo 完全虚构；imported 人工导入，非实时接入）`,`生成时间：${now}`,'',`今日更新关注：${alerts.length}`,...alerts.flatMap(a=>[`${a.symbol}：${a.title}｜关注分 ${a.score}｜${a.status}`,`证据时间 ${a.payload.snapshot_at}；来源 ${a.payload.source}`]),'',run?`最近扫描：${run.status} / ${run.detail}`:'尚无扫描记录','缺失、失败或过期不等于市场无异常。',PAPER_DISABLED,'无券商、真实下单、实时抓取或全天监控。'].join('\n');}
export function view(s,now){const snaps=latest(s,s.mode);return {...s,snapshots:undefined,sequence:undefined,server_time:now,timezone:'Asia/Shanghai',csrf_token:'same-origin-required',paper:null,hosted_paper_disabled:true,watchlist:s.watchlist.map(w=>({...w,snapshot:snaps[w.symbol]?{...snaps[w.symbol],freshness:freshness(snaps[w.symbol],now)}:null})),alerts:s.alerts.filter(a=>a.mode===s.mode).sort((a,b)=>b.score-a.score||b.updated_at.localeCompare(a.updated_at)).slice(0,100).map(a=>({...a,evidence_stale:s.mode!=='demo'&&(Date.parse(now)-Date.parse(a.payload.snapshot_at))>(a.kind==='news'?72*3600000:20*60000)})),news:s.news.filter(n=>n.mode===s.mode).sort((a,b)=>b.published_at.localeCompare(a.published_at)).slice(0,100),runs:s.runs.filter(r=>r.mode===s.mode).slice(0,12),audit:s.audit.slice(0,30),digest:digest(s,now),monitor:{persistent:false,live_adapter:false,broker_api:false,freshness_minutes:20,description:'云端按需扫描；无行情抓取或外部通知'},rule_version:RULE};}
