<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import type { FormInstance, FormRules, UploadFile } from 'element-plus';
import { readWorkspace, request } from './api';
import { expectations, formatDate, navigation, number, reactions, stages, statuses, verifications } from './types';
import type { Alert, News, Page, WatchItem, Workspace } from './types';
const state=ref<Workspace|null>(null),loading=ref(true),busy=ref(false),error=ref('');
function initialPage():Page{const hash=location.hash.slice(1);return navigation.some(n=>n.key===hash)?hash as Page:'overview'}
const page=ref<Page>(initialPage()),pageTitle=computed(()=>navigation.find(n=>n.key===page.value)?.label||'研究总览');
const watchlist=computed(()=>state.value?.watchlist.filter(w=>state.value?.mode==='demo'?w.symbol.startsWith('DEMO'):!w.symbol.startsWith('DEMO'))||[]);
const pending=computed(()=>state.value?.alerts.filter(a=>a.status==='new').length||0);
const currentMode=computed(()=>state.value?.mode==='demo'?'虚构演示':state.value?.mode==='live'?'实时未接入':'人工导入');
const modeDescription=computed(()=>state.value?.mode==='demo'?'仅在执行扫描时生成虚构样本，不代表真实证券或公司事实':state.value?.mode==='live'?'实时行情适配器尚未接入，扫描将明确失败，不回退到演示数据':'仅分析人工导入的快照；来源、统计口径与时效仍需人工核验');
function navigate(value:string){if(navigation.some(n=>n.key===value)){page.value=value as Page;location.hash=value}}
async function load(){try{state.value=await readWorkspace();error.value=''}catch(e){error.value=e instanceof Error?e.message:'无法读取工作区';throw e}finally{loading.value=false}}
async function refresh(){try{await load()}catch{ElMessage.error(error.value)}}
async function mutate<T>(path:string,data:unknown):Promise<T>{return request<T>(path,data,state.value?.csrf_token)}
async function changeMode(mode:string){if(busy.value)return;busy.value=true;try{await mutate('/api/mode',{mode});await load()}catch(e){ElMessage.error(message(e))}finally{busy.value=false}}
async function scan(){if(busy.value)return;busy.value=true;try{const result=await mutate<{detail:string;status:string}>('/api/run',{mode:state.value?.mode});await load();if(result.status==='failed')ElMessage.error(result.detail);else ElMessage({message:result.detail,type:result.status==='ok'?'success':'warning',duration:6000})}catch(e){ElMessage.error(message(e))}finally{busy.value=false}}
function message(e:unknown){return e instanceof Error?e.message:'操作失败，请保留输入并重试'}
function company(symbol:string){return state.value?.watchlist.find(w=>w.symbol===symbol)?.name||symbol}
function downloadDigest(){if(!state.value)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([state.value.digest],{type:'text/plain;charset=utf-8'}));a.download=`starfolio-${state.value.mode}-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const watchDialog=ref(false),editingWatch=ref(false),watchForm=ref<FormInstance>(),watchDraft=reactive({symbol:'',name:''}),formError=ref('');
const watchRules:FormRules={symbol:[{required:true,message:'请输入证券代码',trigger:'blur'},{pattern:/^(\d{6}|DEMO0[1-4])$/,message:'请输入六位代码',trigger:'blur'}],name:[{required:true,message:'请输入证券名称',trigger:'blur'},{max:50,message:'名称最多 50 字符',trigger:'blur'}]};
function openWatch(item?:WatchItem){Object.assign(watchDraft,{symbol:item?.symbol||'',name:item?.name||''});editingWatch.value=!!item;formError.value='';watchDialog.value=true}
async function saveWatch(){if(busy.value)return;if(!watchDraft.symbol.trim()||!watchDraft.name.trim()){formError.value='请输入证券代码和名称';await watchForm.value?.validate().catch(()=>false);return}if(!await watchForm.value?.validate().catch(()=>false))return;busy.value=true;try{await mutate('/api/watchlist',{...watchDraft});await load();watchDialog.value=false;ElMessage.success('自选已保存')}catch(e){formError.value=message(e)}finally{busy.value=false}}
async function removeWatch(item:WatchItem){try{await ElMessageBox.confirm(`从自选移除 ${item.name}（${item.symbol}）？已有证据与审计将保留。`,'移除自选',{confirmButtonText:'确认移除',cancelButtonText:'取消',type:'warning'});busy.value=true;await mutate('/api/watchlist/remove',{symbol:item.symbol});await load();ElMessage.success('已移除自选')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e))}finally{busy.value=false}}
const newsDialog=ref(false),newsForm=ref<FormInstance>();
function blankNews(){return {symbol:'',title:'',stage:'unknown',verification:'unverified',source_url:'',source:'',published_at:new Date().toISOString(),reviewed_by:'',evidence_excerpt:'',expectation_status:'unknown',expectation_evidence:'',price_reaction:'unknown',price_reaction_evidence:'',amount:'',note:''}}
const newsDraft=reactive(blankNews());
const newsRules:FormRules={symbol:[{required:true,message:'请输入证券代码',trigger:'blur'},{pattern:/^\d{6}$/,message:'请输入六位代码',trigger:'blur'}],title:[{required:true,message:'请输入标题',trigger:'blur'}],source_url:[{required:true,message:'请输入原始 HTTPS 链接',trigger:'blur'},{pattern:/^https:\/\//,message:'须为 HTTPS 链接',trigger:'blur'}],source:[{required:true,message:'请输入来源名称',trigger:'blur'}],published_at:[{required:true,message:'请输入含时区的发布时间',trigger:'blur'}]};
function openNews(item?:News){Object.assign(newsDraft,item||blankNews());formError.value='';newsDialog.value=true}
async function saveNews(){if(busy.value||!await newsForm.value?.validate().catch(()=>false))return;busy.value=true;try{await mutate('/api/news',{...newsDraft});if(state.value?.mode!=='imported')await mutate('/api/mode',{mode:'imported'});await load();newsDialog.value=false;ElMessage.success('证据已保存；研究状态保持 HOLD')}catch(e){formError.value=message(e)}finally{busy.value=false}}
const importDialog=ref(false),importKind=ref<'market'|'portfolio'>('market'),importText=ref('');
function openImport(kind:'market'|'portfolio'){importKind.value=kind;importText.value='';formError.value='';importDialog.value=true}
async function readFile(file:UploadFile){if(!file.raw)return;if(file.raw.size>500000){formError.value='文件须小于 500 KB';return}importText.value=await file.raw.text();formError.value=''}
async function submitImport(){if(busy.value)return;if(!importText.value.trim()){formError.value='请选择文件或粘贴内容';return}try{if(importKind.value==='portfolio')await ElMessageBox.confirm('这些证券、数量与成本将上传到你的私有云端，并替换已有持仓参考。不要包含账户、身份或凭证。','确认导入持仓',{confirmButtonText:'确认上传并替换',cancelButtonText:'取消',type:'warning'});busy.value=true;if(importKind.value==='market'){const snapshots=JSON.parse(importText.value);await mutate('/api/import/market',{snapshots});await mutate('/api/mode',{mode:'imported'})}else await mutate('/api/import/portfolio',{csv:importText.value});await load();importDialog.value=false;ElMessage.success('已保存到私有云端')}catch(e){if(e!=='cancel'&&e!=='close')formError.value=message(e)}finally{busy.value=false}}
const detailAlert=ref<Alert|null>(null),detailOpen=ref(false),reviewNote=ref('');
function showAlert(alert:Alert){detailAlert.value=alert;reviewNote.value='';detailOpen.value=true}
async function markAlert(status:string){if(!detailAlert.value||busy.value)return;busy.value=true;try{await mutate('/api/alerts/status',{id:detailAlert.value.id,status,note:reviewNote.value});await load();detailOpen.value=false;ElMessage.success('复核状态已保存')}catch(e){ElMessage.error(message(e))}finally{busy.value=false}}
let timer:ReturnType<typeof setInterval>|undefined;let modelContextLifecycle:AbortController|undefined;
function hashChanged(){page.value=initialPage()}
onMounted(()=>{void load().catch(()=>{});window.addEventListener('hashchange',hashChanged);timer=setInterval(()=>{if(!document.hidden&&!busy.value&&!watchDialog.value&&!newsDialog.value&&!importDialog.value&&!detailOpen.value)void load().catch(()=>{})},30000);
 const context=(document as Document&{modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>unknown}}).modelContext;if(context?.registerTool){modelContextLifecycle=new AbortController();for(const tool of [{name:'read_investment_workspace',description:'Read current authenticated research records; no market feed or trades.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{await load();return {mode:state.value?.mode,watchlist:watchlist.value,news:state.value?.news,hosted_paper_disabled:true}}},{name:'save_watchlist_item',description:'Save a private watchlist item using the same form API, refresh the visible list; no price fetch or trades.',inputSchema:{type:'object',properties:{symbol:{type:'string',pattern:'^[0-9]{6}$'},name:{type:'string',minLength:1,maxLength:50}},required:['symbol','name'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:{symbol:string;name:string})=>{if(!input||!/^\d{6}$/.test(input.symbol)||typeof input.name!=='string'||!input.name.trim()||input.name.length>50)throw new Error('请输入六位代码及名称');const result=await mutate('/api/watchlist',{symbol:input.symbol,name:input.name});await load();navigate('watchlist');return result}}]){try{void Promise.resolve(context.registerTool(tool,{signal:modelContextLifecycle.signal})).catch(()=>{})}catch{}}}
});
onUnmounted(()=>{if(timer)clearInterval(timer);window.removeEventListener('hashchange',hashChanged);modelContextLifecycle?.abort()});
</script>

<template>
  <el-container class="workspace-shell">
    <el-aside width="224px" class="workspace-sidebar">
      <a class="brand" href="#overview" @click="navigate('overview')"><span class="brand-mark">星</span><span>星策<small>STARFOLIO</small></span></a>
      <p class="nav-caption">个人研究工作台</p>
      <el-menu :default-active="page" class="workspace-menu" @select="navigate"><el-menu-item v-for="item in navigation" :key="item.key" :index="item.key">{{ item.label }}</el-menu-item></el-menu>
      <div class="sidebar-note"><el-tag effect="plain" type="success">仅本人访问</el-tag><p>Vue 3 · Element Plus<br>无券商连接 · 零实盘订单</p></div>
    </el-aside>
    <el-container class="workspace-body">
      <el-header class="workspace-header"><div class="header-title"><span class="mobile-brand">星策</span><el-breadcrumb separator="/"><el-breadcrumb-item>工作台</el-breadcrumb-item><el-breadcrumb-item>{{ pageTitle }}</el-breadcrumb-item></el-breadcrumb></div><div class="header-meta"><span>{{ state ? formatDate(state.server_time) : '上海时间' }}</span><el-tag type="success" effect="plain">私有云端</el-tag></div></el-header>
      <el-main class="workspace-main">
        <el-select :model-value="page" class="mobile-navigation" aria-label="切换页面" @change="navigate"><el-option v-for="item in navigation" :key="item.key" :label="item.label" :value="item.key" /></el-select>
        <div class="page-toolbar"><div><h1>{{ pageTitle }}</h1><p>先看证据，再讨论行动</p></div><el-space wrap><el-button :disabled="!state" @click="downloadDigest">导出日报</el-button><el-button :loading="busy" :disabled="!state" type="primary" @click="scan">执行一次扫描</el-button></el-space></div>
        <el-alert v-if="error" :title="error" description="当前内容可能未更新；保存失败时请保留输入，不会显示为新行情" type="error" :closable="false" show-icon class="section-gap"><el-button text type="primary" @click="refresh">重新加载</el-button></el-alert>
        <el-skeleton v-if="loading" :rows="8" animated />
        <el-result v-else-if="!state" icon="warning" title="暂时无法读取工作区" sub-title="请确认登录与网络后重试"><template #extra><el-button type="primary" @click="refresh">重新加载</el-button></template></el-result>
        <template v-else>
          <el-alert :title="currentMode + ' · ' + modeDescription" :type="state.mode==='demo'?'warning':'info'" :closable="false" show-icon class="section-gap" />
          <template v-if="page==='overview'">
            <div class="stat-grid"><el-card shadow="never"><el-statistic title="自选研究对象" :value="watchlist.length" /><p class="muted">{{ state.mode==='demo'?'虚构样本':'仅已添加的证券' }}</p></el-card><el-card shadow="never"><el-statistic title="待人工复核" :value="pending" /><p class="muted">规则关注，不是买卖建议</p></el-card><el-card shadow="never"><el-statistic title="实时源覆盖" :value="0" /><p class="muted">行情与新闻接口未接入</p></el-card><el-card shadow="never"><span class="muted">执行状态</span><h2>按需扫描</h2><p class="muted">无全天监控或外部推送</p></el-card></div>
            <el-card shadow="never" class="section-gap"><template #header><div class="card-header"><h2>优先复核</h2><el-button text type="primary" @click="navigate('alerts')">全部提醒</el-button></div></template><el-empty v-if="!state.alerts.length" description="暂无异常证据。请先检查是否有可分析的新鲜数据" /><el-table v-else :data="state.alerts.slice(0,5)" stripe><el-table-column label="研究对象" min-width="150"><template #default="{row}">{{ company(row.symbol) }}<small class="cell-meta">{{ row.symbol }}</small></template></el-table-column><el-table-column prop="title" label="关注事件" min-width="260" /><el-table-column label="关注分" width="95"><template #default="{row}"><el-tag effect="plain">{{ row.score }}</el-tag></template></el-table-column><el-table-column label="状态" width="115"><template #default="{row}">{{ statuses[row.status] }}</template></el-table-column><el-table-column label="复核" width="110"><template #default="{row}"><el-button link type="primary" @click="showAlert(row as Alert)">查看证据</el-button></template></el-table-column></el-table></el-card>
            <el-card shadow="never"><template #header><h2>研究边界</h2></template><el-alert title="大单分类不能识别真实机构身份，价格反应不能证明事实阶段" type="warning" :closable="false" /><p>应用、试点、订单、收入须分别核验；相对预期与价格观察独立记录。证据不完整时保持 HOLD，不自动生成交易。</p><el-space wrap><el-button @click="navigate('watchlist')">管理自选</el-button><el-button @click="navigate('news')">录入事件证据</el-button><el-button @click="navigate('settings')">检查数据接入</el-button></el-space></el-card>
          </template>
          <template v-if="page==='watchlist'">
            <el-card shadow="never" class="section-gap"><template #header><div class="card-header"><h2>{{ state.mode==='demo'?'虚构演示自选':'自选清单' }}</h2><el-button type="primary" @click="openWatch()">添加自选</el-button></div></template><el-table :data="watchlist" stripe empty-text="尚无自选标的。添加代码不会自动抓取行情"><el-table-column label="研究对象" min-width="155"><template #default="{row}"><strong>{{ row.name }}</strong><small class="cell-meta">{{ row.symbol }}</small></template></el-table-column><el-table-column label="价格 / 涨跌幅" min-width="155"><template #default="{row}">{{ number(row.snapshot?.price) }}<small v-if="row.snapshot" class="cell-meta">{{ number(row.snapshot.change_pct) }}%</small></template></el-table-column><el-table-column label="成交额（元）" min-width="150"><template #default="{row}">{{ number(row.snapshot?.turnover) }}</template></el-table-column><el-table-column label="数据状态" min-width="210"><template #default="{row}"><el-tag :type="row.snapshot?.freshness.state==='fresh'?'success':row.snapshot?'warning':'info'">{{ row.snapshot?.freshness.label||'未接入' }}</el-tag><small v-if="row.snapshot" class="cell-meta">{{ formatDate(row.snapshot.observed_at) }}</small></template></el-table-column><el-table-column label="操作" width="145" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openWatch(row as WatchItem)">编辑</el-button><el-button link type="danger" :disabled="busy" @click="removeWatch(row as WatchItem)">移除</el-button></template></el-table-column></el-table></el-card>
            <el-card shadow="never"><template #header><h2>半导体与存储研究线索</h2></template><div class="theme-grid"><div v-for="topic in [['存储设计','NOR、NAND、DRAM；核对产品结构、价格与研发兑现'],['模组与品牌','内存条、SSD、嵌入式模组；核对库存、采购价与毛利'],['制造与封测','晶圆产能、先进封装；核对稼动率、良率与资本开支'],['设备与材料','设备、耗材、材料；核对验证、订单与验收周期']]" :key="topic[0]"><h3>{{ topic[0] }}</h3><p class="muted">{{ topic[1] }}</p></div></div><el-text type="info">主题关联只是研究起点，不代表订单、收入或投资价值</el-text></el-card>
          </template>
          <template v-if="page==='news'">
            <el-alert title="事实阶段、相对预期、价格反应各自需要证据，互不证明；未知保持 HOLD" type="warning" :closable="false" show-icon class="section-gap" />
            <el-card shadow="never"><template #header><div class="card-header"><h2>公告与消息记录</h2><el-button type="primary" @click="openNews()">录入证据</el-button></div></template><el-empty v-if="!state.news.length" description="等待第一条原始证据。建议从交易所、公司公告与财报原文开始" /><div v-for="item in state.news" :key="item.id" class="news-record"><div class="card-header"><el-space wrap><el-tag>{{ stages[item.stage] }}</el-tag><el-tag type="info">{{ verifications[item.verification] }}</el-tag><el-tag type="warning">HOLD</el-tag></el-space><el-button text type="primary" @click="openNews(item)">更新记录</el-button></div><h3>{{ item.title }}</h3><el-descriptions :column="1" border><el-descriptions-item label="原文依据">{{ item.evidence_excerpt||'未提供，价格不能补充事实证明' }}</el-descriptions-item><el-descriptions-item label="相对预期">{{ expectations[item.expectation_status] }}<p class="evidence-text">{{ item.expectation_evidence||'暂无事前比较基准与证据' }}</p></el-descriptions-item><el-descriptions-item label="价格反应">{{ reactions[item.price_reaction] }}<p class="evidence-text">{{ item.price_reaction_evidence||'暂无观察窗口、来源与证据' }}</p></el-descriptions-item><el-descriptions-item label="研究状态">{{ item.research_assessment.reason }}</el-descriptions-item></el-descriptions><div class="record-footer"><span class="muted">{{ item.symbol }} · {{ item.source }} · {{ formatDate(item.published_at) }}</span><el-link v-if="item.source_url" :href="item.source_url" target="_blank" rel="noopener noreferrer" type="primary">打开原始出处</el-link></div></div></el-card>
          </template>
          <template v-if="page==='portfolio'">
            <el-card shadow="never" class="section-gap"><template #header><el-space wrap><h2>模拟账户</h2><el-tag type="warning">云端未启用</el-tag></el-space></template><el-alert title="云端不会生成模拟订单、成交、余额或策略收益" type="warning" :closable="false" show-icon /><p>Python v2 已实现基础纸面撮合、分批止盈和移动止盈测试；尚未迁移至这里的云端账本。T+1、明确交易日历、证据接收时间、严格后续报价、费用与现金约束需要一起验证。</p><el-text type="info">所有模拟决策、报价撮合与退出计划写入接口均关闭；没有真实交易接口</el-text></el-card>
            <el-card shadow="never"><template #header><div class="card-header"><h2>持仓参考 · 私有云端记录</h2><el-button type="primary" @click="openImport('portfolio')">导入 CSV</el-button></div></template><el-alert title="手工导入仅供参考，无券商连接；不要填写账号、身份或凭证" type="info" :closable="false" class="section-gap" /><el-table :data="state.portfolio" stripe empty-text="尚未导入持仓参考"><el-table-column prop="symbol" label="代码" min-width="110" /><el-table-column prop="name" label="证券名称" min-width="150" /><el-table-column label="股数" min-width="100"><template #default="{row}">{{ number(row.shares) }}</template></el-table-column><el-table-column label="成本价（元）" min-width="130"><template #default="{row}">{{ number(row.cost) }}</template></el-table-column><el-table-column label="导入时间" min-width="190"><template #default="{row}">{{ formatDate(row.imported_at) }}</template></el-table-column></el-table></el-card>
          </template>
          <template v-if="page==='alerts'">
            <el-card shadow="never"><el-tabs><el-tab-pane label="关注事件"><el-table :data="state.alerts" stripe empty-text="暂无提醒；请先确认数据是否接入、是否过期"><el-table-column prop="symbol" label="代码" width="110" /><el-table-column prop="title" label="关注事件" min-width="260" /><el-table-column label="关注分" width="95"><template #default="{row}">{{ row.score }}</template></el-table-column><el-table-column label="状态" min-width="170"><template #default="{row}"><el-tag :type="row.evidence_stale?'warning':'info'">{{ row.evidence_stale?'证据已过期':statuses[row.status] }}</el-tag></template></el-table-column><el-table-column label="操作" width="110"><template #default="{row}"><el-button link type="primary" @click="showAlert(row as Alert)">查看证据</el-button></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="最近扫描"><el-table :data="state.runs" stripe empty-text="尚无扫描记录"><el-table-column label="开始时间" min-width="190"><template #default="{row}">{{ formatDate(row.started_at) }}</template></el-table-column><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="mode" label="工作区" width="110" /><el-table-column prop="detail" label="结果" min-width="300" /></el-table></el-tab-pane><el-tab-pane label="操作审计"><el-table :data="state.audit" stripe empty-text="尚无操作记录"><el-table-column label="时间" min-width="190"><template #default="{row}">{{ formatDate(row.at) }}</template></el-table-column><el-table-column prop="action" label="操作" min-width="150" /><el-table-column prop="target" label="对象" min-width="140" /><el-table-column prop="detail" label="记录详情" min-width="300" show-overflow-tooltip /></el-table></el-tab-pane></el-tabs></el-card>
          </template>
          <template v-if="page==='settings'">
            <el-card shadow="never" class="section-gap"><template #header><h2>数据工作区</h2></template><el-form label-position="top"><el-form-item label="当前模式"><el-select :model-value="state.mode" :disabled="busy" class="mode-select" @change="changeMode"><el-option label="人工导入 · 非实时行情" value="imported" /><el-option label="演示 · 完全虚构样本" value="demo" /><el-option label="实时 · 尚未接入" value="live" /></el-select></el-form-item></el-form><p class="muted">切换模式不会自动抓取数据。行情超过 {{ state.monitor.freshness_minutes }} 分钟，停止生成新资金异常提醒。页面每 30 秒仅刷新已保存的云端状态。</p><el-button type="primary" @click="openImport('market')">导入行情 JSON</el-button></el-card>
            <el-card shadow="never" class="section-gap"><template #header><h2>接入状态</h2></template><el-descriptions :column="1" border><el-descriptions-item label="行情与历史">未接入自动行情服务；人工导入须提供来源、观察时间与同窗基线</el-descriptions-item><el-descriptions-item label="公告与新闻">手工录入；系统不自动抓取原文、不独立验证事实</el-descriptions-item><el-descriptions-item label="资金流 / L2">未接入逐笔数据；大单口径不能识别真实机构</el-descriptions-item><el-descriptions-item label="模型与券商">均未接入；没有密钥输入框、券商或真实下单端点</el-descriptions-item><el-descriptions-item label="监控与通知">仅按需扫描；托管不代表已配置全天行情监控或通知</el-descriptions-item><el-descriptions-item label="模拟执行">云端关闭；Python v2 测试实现独立保留</el-descriptions-item></el-descriptions></el-card>
            <el-card shadow="never"><template #header><h2>运行与访问</h2></template><el-descriptions :column="1" border><el-descriptions-item label="界面组件">Vue 3 + Element Plus</el-descriptions-item><el-descriptions-item label="访问范围">仅本人 · ChatGPT 登录，所有数据接口校验身份</el-descriptions-item><el-descriptions-item label="持久化">D1 · 原子保存、并发检查、操作去重与审计</el-descriptions-item><el-descriptions-item label="规则版本">{{ state.rule_version }} · 关注分不是收益概率</el-descriptions-item></el-descriptions></el-card>
          </template>
          <footer class="workspace-footer">星策 · 研究记录与人工复核，不构成买卖指令<span>Asia/Shanghai · 数据保留来源</span></footer>
        </template>
      </el-main>
    </el-container>
  </el-container>

  <el-dialog v-model="watchDialog" :title="editingWatch?'编辑自选':'添加自选'" width="min(520px, 94vw)" :close-on-click-modal="false" destroy-on-close>
    <el-alert v-if="formError" :title="formError" type="error" :closable="false" class="section-gap" />
    <el-form ref="watchForm" :model="watchDraft" :rules="watchRules" label-position="top" @submit.prevent="saveWatch"><el-form-item label="证券代码" prop="symbol"><el-input v-model="watchDraft.symbol" :disabled="editingWatch" placeholder="六位证券代码" maxlength="6" /></el-form-item><el-form-item label="证券名称" prop="name"><el-input v-model="watchDraft.name" maxlength="50" /></el-form-item></el-form><p class="muted">添加代码不会生成报价或自动抓取行情</p>
    <template #footer><el-button @click="watchDialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="saveWatch">保存自选</el-button></template>
  </el-dialog>
  <el-dialog v-model="newsDialog" title="录入消息与独立研究证据" width="min(820px, 94vw)" :close-on-click-modal="false" destroy-on-close>
    <el-alert v-if="formError" :title="formError" type="error" :closable="false" class="section-gap" />
    <el-form ref="newsForm" :model="newsDraft" :rules="newsRules" label-position="top" @submit.prevent="saveNews"><div class="form-grid"><el-form-item label="证券代码" prop="symbol"><el-input v-model="newsDraft.symbol" maxlength="6" /></el-form-item><el-form-item label="事实阶段"><el-select v-model="newsDraft.stage"><el-option v-for="(label,value) in stages" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="标题" prop="title" class="full-width"><el-input v-model="newsDraft.title" maxlength="200" /></el-form-item><el-form-item label="原始 HTTPS 链接" prop="source_url" class="full-width"><el-input v-model="newsDraft.source_url" maxlength="1500" placeholder="https://" /></el-form-item><el-form-item label="来源名称" prop="source"><el-input v-model="newsDraft.source" maxlength="150" /></el-form-item><el-form-item label="发布时间（含时区）" prop="published_at"><el-input v-model="newsDraft.published_at" placeholder="2026-10-05T09:00:00+08:00" /></el-form-item><el-form-item label="核验状态"><el-select v-model="newsDraft.verification"><el-option label="待核验" value="unverified" /><el-option label="已有链接 · 尚未核验" value="linked" /><el-option label="我已阅读原文并人工核验" value="reviewed" /></el-select></el-form-item><el-form-item label="核验人（人工核验时必填）"><el-input v-model="newsDraft.reviewed_by" maxlength="60" /></el-form-item><el-form-item label="事实原文依据 / 限制条件" class="full-width"><el-input v-model="newsDraft.evidence_excerpt" type="textarea" :rows="3" maxlength="3000" show-word-limit placeholder="非未知事实阶段须填写。不能用价格涨跌代替原文依据" /></el-form-item><el-form-item label="相对预期（独立人工判断）"><el-select v-model="newsDraft.expectation_status"><el-option v-for="(label,value) in expectations" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="价格反应（独立观察）"><el-select v-model="newsDraft.price_reaction"><el-option v-for="(label,value) in reactions" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="预期比较依据" class="full-width"><el-input v-model="newsDraft.expectation_evidence" type="textarea" :rows="3" maxlength="3000" show-word-limit placeholder="事前预期来源、时间、比较基准及限制；不能仅凭涨跌声称已计价" /></el-form-item><el-form-item label="价格观察依据" class="full-width"><el-input v-model="newsDraft.price_reaction_evidence" type="textarea" :rows="3" maxlength="3000" show-word-limit placeholder="起止时间、报价来源、观察数值及市场/板块对照" /></el-form-item><el-form-item label="披露金额"><el-input v-model="newsDraft.amount" maxlength="80" placeholder="未披露请留空" /></el-form-item><el-form-item label="研究备注"><el-input v-model="newsDraft.note" maxlength="1000" /></el-form-item></div></el-form>
    <el-alert title="各维度独立核验；保存不会产生模拟买卖决策，研究状态保持 HOLD" type="info" :closable="false" />
    <template #footer><el-button @click="newsDialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="saveNews">保存核验记录</el-button></template>
  </el-dialog>
  <el-dialog v-model="importDialog" :title="importKind==='market'?'导入行情 JSON':'导入持仓 CSV'" width="min(720px, 94vw)" :close-on-click-modal="false" destroy-on-close>
    <el-alert v-if="formError" :title="formError" type="error" :closable="false" class="section-gap" />
    <el-upload :auto-upload="false" :show-file-list="false" :accept="importKind==='market'?'.json':'.csv'" :on-change="readFile"><el-button>选择本机文件</el-button><template #tip><div class="el-upload__tip">文件仅在点击确认导入后发送到私有云端，最大 500 KB</div></template></el-upload>
    <el-form label-position="top" class="section-top"><el-form-item label="文件内容 / 可直接粘贴"><el-input v-model="importText" type="textarea" :rows="12" :placeholder="importKind==='portfolio'?'symbol,name,shares,cost\n600000,示例名称,100,10':'[ { &quot;symbol&quot;: &quot;600000&quot;, &quot;observed_at&quot;: &quot;含时区的时间&quot;, … } ]'" /></el-form-item></el-form>
    <el-alert v-if="importKind==='portfolio'" title="须恰好包含 symbol,name,shares,cost 四列；将上传并替换私有云端持仓参考" description="不要填写账号、身份或凭证。示例证券与数值仅表示格式" type="warning" :closable="false" />
    <el-collapse v-else><el-collapse-item title="行情 JSON 字段与核验要求" name="contract"><p>数组 1–100 项。必填 symbol、observed_at（带时区）、source、source_url（HTTPS）、price、turnover、volume、change_pct。</p><p>可选 baseline（最多 120 个同窗成交额）须注明 baseline_basis；large_order_net 须注明 flow_definition。series 最多 60 项。数值须有限且单位一致，未来行情拒绝导入。</p><p>旧行情可以保存供研究，但超过 20 分钟不会生成新的资金提醒。</p></el-collapse-item></el-collapse>
    <template #footer><el-button @click="importDialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="submitImport">确认导入</el-button></template>
  </el-dialog>
  <el-drawer v-model="detailOpen" title="证据与反证" size="min(650px, 96vw)">
    <template v-if="detailAlert"><el-space wrap><el-tag>{{ detailAlert.symbol }}</el-tag><el-tag type="warning">关注分 {{ detailAlert.score }} / 非概率</el-tag></el-space><h2>{{ detailAlert.title }}</h2><el-alert :title="detailAlert.payload.hypothesis" type="info" :closable="false" /><h3>触发证据</h3><ul><li v-for="item in detailAlert.payload.evidence" :key="item">{{ item }}</li></ul><h3>另一种解释</h3><ul><li v-for="item in detailAlert.payload.counter_evidence" :key="item">{{ item }}</li></ul><h3>失效条件</h3><ul><li v-for="item in detailAlert.payload.invalidation" :key="item">{{ item }}</li></ul><el-descriptions :column="1" border><el-descriptions-item label="来源">{{ detailAlert.payload.source }}</el-descriptions-item><el-descriptions-item label="证据时间">{{ formatDate(detailAlert.payload.snapshot_at) }}</el-descriptions-item><el-descriptions-item label="规则">{{ detailAlert.payload.rule_version }}</el-descriptions-item></el-descriptions><p><el-link v-if="detailAlert.payload.source_url" :href="detailAlert.payload.source_url" target="_blank" rel="noopener noreferrer" type="primary">打开原始出处</el-link></p><p>{{ detailAlert.payload.question }}</p><el-alert :title="detailAlert.payload.disclaimer" type="warning" :closable="false" /><el-form label-position="top" class="section-top"><el-form-item label="复核备注（可选）"><el-input v-model="reviewNote" type="textarea" :rows="3" maxlength="500" /></el-form-item></el-form></template>
    <template #footer><el-button :disabled="busy" @click="markAlert('dismissed')">忽略</el-button><el-button type="primary" :loading="busy" @click="markAlert('reviewed')">标记已复核</el-button></template>
  </el-drawer>
</template>
