import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { mount,flushPromises } from '@vue/test-utils';
import type { VueWrapper } from '@vue/test-utils';
import ElementPlus from 'element-plus';
import zhCn from 'element-plus/es/locale/lang/zh-cn';
import ResearchWorkspace from '../ui/ResearchWorkspace.vue';
import { initialState,mutate,view } from '../lib/watch-engine.mjs';
let data: {watchlist:{name:string}[];runs:{status:string}[];snapshots:unknown[];[key:string]:unknown}=initialState();let wrapper:VueWrapper|undefined;let calls:{url:string;data:unknown}[]=[];
const now='2026-10-05T01:00:00.000Z';
async function settle(){await flushPromises();await new Promise(r=>setTimeout(r,20));await flushPromises()}
function button(label:string){const buttons=[...document.querySelectorAll('button')];const b=buttons.find(x=>x.textContent?.trim()===label);if(!b)throw Error(`Button not found: ${label}`);return b as HTMLButtonElement}
async function click(label:string){button(label).click();await settle()}
async function selectPage(label:string){const item=[...document.querySelectorAll('.el-menu-item')].find(x=>x.textContent?.trim()===label) as HTMLElement;item.click();await settle()}
beforeEach(()=>{location.hash='';data=initialState();calls=[];vi.stubGlobal('fetch',vi.fn(async(url:string,options?:RequestInit)=>{if(options?.method==='POST'){const input=JSON.parse(String(options.body));calls.push({url,data:input});try{return Response.json(mutate(data,url,input,now))}catch(e){return Response.json({error:e instanceof Error?e.message:'error'},{status:400})}}return Response.json(view(data,now))}));wrapper=mount(ResearchWorkspace,{attachTo:document.body,global:{plugins:[[ElementPlus,{locale:zhCn}]]}})});
afterEach(()=>{wrapper?.unmount();document.body.innerHTML='';vi.unstubAllGlobals()});
describe('Vue 3 / Element Plus management flows (DOM component tests, not browser QA)',()=>{
 it('renders empty private state and genuine Element Plus table/menu',async()=>{await settle();expect(document.querySelector('.el-menu')).not.toBeNull();expect(wrapper?.text()).toContain('仅本人访问');await selectPage('自选与主题');expect(document.querySelector('.el-table')).not.toBeNull();expect(wrapper?.text()).toContain('尚无自选标的')});
 it('adds a watch item through the Element Plus form and persists via existing API',async()=>{await settle();await selectPage('自选与主题');await click('添加自选');const inputs=document.querySelectorAll('.el-dialog input');(inputs[0] as HTMLInputElement).value='600000';inputs[0].dispatchEvent(new Event('input',{bubbles:true}));(inputs[1] as HTMLInputElement).value='组件测试';inputs[1].dispatchEvent(new Event('input',{bubbles:true}));await click('保存自选');expect(calls.some(c=>c.url==='/api/watchlist')).toBe(true);expect(data.watchlist[0]?.name).toBe('组件测试');expect(wrapper?.text()).toContain('组件测试')});
 it('validation prevents an invalid watchlist request',async()=>{await settle();await selectPage('自选与主题');await click('添加自选');await click('保存自选');expect(calls,JSON.stringify(calls)).toHaveLength(0);expect(document.body.textContent).toContain('请输入证券代码')});
 it('news dialog exposes independent fact/expectation/price evidence',async()=>{await settle();await selectPage('事件核验');await click('录入证据');expect(document.body.textContent).toContain('事实原文依据');expect(document.body.textContent).toContain('预期比较依据');expect(document.body.textContent).toContain('价格观察依据');expect(document.querySelectorAll('.el-dialog textarea').length).toBe(3)});
 it('market import preserves invalid input and error without a data write',async()=>{await settle();await selectPage('数据与设置');await click('导入行情 JSON');const t=document.querySelector('.el-dialog textarea') as HTMLTextAreaElement;t.value='invalid-json';t.dispatchEvent(new Event('input',{bubbles:true}));await click('确认导入');expect(calls.length).toBe(0);expect(t.value).toBe('invalid-json');expect(document.querySelector('.el-dialog .el-alert--error')).not.toBeNull()});
 it('paper page has no order controls or balances and no paper API calls',async()=>{await settle();await selectPage('持仓与模拟');expect(wrapper?.text()).toContain('云端未启用');expect(wrapper?.text()).toContain('所有模拟决策');expect([...document.querySelectorAll('button')].some(b=>b.textContent?.includes('模拟决策'))).toBe(false);expect(calls.every(c=>!c.url.startsWith('/api/paper/'))).toBe(true)});
 it('scan creates only a manual degraded run for empty imported state',async()=>{await settle();await click('执行一次扫描');expect(calls[0]?.url).toBe('/api/run');expect(data.runs[0]?.status).toBe('degraded');expect(data.snapshots.length).toBe(0)});
 it('server failure is visible and does not erase an unsaved form',async()=>{await settle();await selectPage('自选与主题');await click('添加自选');const inputs=document.querySelectorAll('.el-dialog input');(inputs[0] as HTMLInputElement).value='600001';inputs[0].dispatchEvent(new Event('input',{bubbles:true}));(inputs[1] as HTMLInputElement).value='保存失败测试';inputs[1].dispatchEvent(new Event('input',{bubbles:true}));vi.stubGlobal('fetch',vi.fn(async()=>Response.json({error:'持久存储暂不可用'},{status:503})));await click('保存自选');expect(document.body.textContent).toContain('持久存储暂不可用');expect((inputs[1] as HTMLInputElement).value).toBe('保存失败测试')});
});
